name: Release Open WebUI Helm Charts

on:
  push:
    branches:
      - main
      - fix-helm-releaser
    # paths:
    #   - "charts/*/Chart.yaml"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container: ghcr.io/element-hq/chart-releaser:cr-push-fix
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add Dependency Repos
        run: |
          helm repo add ollama https://otwld.github.io/ollama-helm/
          helm repo add open-webui https://helm.openwebui.com/

      - name: Run chart-releaser
        uses: element-hq/chart-releaser-action@1389a6afc9af1b11ab9e79267f371d694e4995b2
        with:
          skip_existing: false
          packages_with_index: true
          charts_dir: charts/
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
